More backdoors
enzocardeal/backdoor-playground pull request #16
Opened 2023-02-08 22:12 UTC by otaviootavio

2023-02-09 17:56 UTC, enzocardeal requested changes

2023-02-09 17:56 UTC, enzocardeal commented on backdoor-playground/resources/database/user-table.json
> +    "password": "1234",
Essa senha vc usa de alguma forma? se sim, tem que passar pelo algoritmo de hash que tá lá na rotina de cadastro

2023-02-09 17:56 UTC, enzocardeal commented on backdoor-playground/src/main/java/br/usp/pcs/backdoor/CreateMaliciousFile.java
> +    private static final String FULL_PATH = "filename.txt";
```suggestion
    private static final String FULL_PATH = "backdoor_trigger.txt";
```

2023-02-09 17:56 UTC, enzocardeal commented on backdoor-playground/src/main/java/br/usp/pcs/backdoor/ThatOneMaliciousException.java
> +        System.out.println("Backdoor of malicious exception!");
No contexto atual, imo, todas as backdoors quando ativadas devem logar como adm

2023-02-09 17:56 UTC, enzocardeal commented on backdoor-playground/src/main/java/br/usp/pcs/control/User.java
> +		if(usernameInput.equals(username) || unhashPassword(passwordHash, passwordInput)) {
Oxe, essa é a rotina de login normal kkk

2023-02-09 18:07 UTC, otaviootavio commented on backdoor-playground/src/main/java/br/usp/pcs/control/User.java
> +		if(usernameInput.equals(username) || unhashPassword(passwordHash, passwordInput)) {
Deveria ser um &&

2023-02-09 18:21 UTC, enzocardeal commented on backdoor-playground/src/main/java/br/usp/pcs/control/User.java
> +		if(usernameInput.equals(username) || unhashPassword(passwordHash, passwordInput)) {
oh

2023-02-09 19:16 UTC, otaviootavio commented on backdoor-playground/resources/database/user-table.json
> +    "password": "1234",
Serve para trigger de backdoor. Idealmente será inserido pelo cadastro de usuário

2023-02-16 22:34 UTC, enzocardeal reviewed
Faz o rebase que eu aprovo

2023-03-09 12:35 UTC, enzocardeal approved these changes

2023-03-19 19:34 UTC, enzocardeal approved these changes

2023-08-03 18:24 UTC, otaviootavio commented
deprecated

2023-08-03 18:24 UTC, closed without merging